version: '3.1'

services:
  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lab1
    ports:
      - "3307:3306"
  lab2:
    image: mysql
    environment:
      MYSQL_HOST: mysql
      DB_PORT: 3307
      MYSQL_ROOT_PASSWORD: password
#      DB_NAME: lab1
#      DB_USER: root
#      DB_PASSWORD: password
#      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8081"
    links:
      - mysql
  lab3:
    image: daneidmark/risk:0.0.1
    ports:
      - "8082:8080"